version: '3'
services:
  postgres:
    restart: always
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod.db
    networks:
      - shared_network

  web:
    restart: always
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env.prod
      - .env.prod.db
    volumes:
      - static_volume:/code/static
    networks:
      - shared_network

volumes:
  postgres_data:
  static_volume:

networks:
  shared_network:
    driver: bridge
