version: '3'
services:
  postgres:
    restart: always
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod.db
    networks:
      - wall_app_api_network

  web:
    restart: always
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env.prod
      - .env.prod.db
    networks:
      - wall_app_api_network

volumes:
  postgres_data:

networks:
  wall_app_api_network:
