version: '3'
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
  web:
    environment:
      - DJANGO_SECRET_KEY=local
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py create_oauth_app &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  local_postgres_data:
  local_postgres_data_backups:
