site_name: wall-app-api
site_description: A place where you can share your ideas.
repo_url: https://github.com/Hercilio1/wall-app-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/Hercilio1">Hercilio1</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
    - Entries: 'api/entries.md'
