# Generated by Django 4.2.1 on 2023-11-04 17:59

from django.db import migrations
import wall-app-api.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', wall-app-api.users.models.CustomUserManager()),
            ],
        ),
    ]
